services:
  survey_database:
    image: postgres:17.4-bookworm
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pg
      POSTGRES_DB: survey_manager
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"

volumes:
  pgdata:
