services:
  survey_frontend:
    container_name: survey_frontend
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - survey_backend
    networks:
      - survey-network

  survey_backend:
    container_name: survey_backend
    build: ./backend
    volumes:
      - shared-storage:/usr/src/app
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://pg:123456@survey_database:5432/survey_manager?schema=public
    depends_on:
      - survey_database
    networks:
      - survey-network

  survey_database:
    image: postgres:17.4-bookworm
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pg
      POSTGRES_DB: survey_manager
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    networks:
      - survey-network

  survey_worker:
    container_name: survey_worker
    build: ./worker
    volumes:
      - shared-storage:/usr/src/app
    depends_on:
      - survey-queue
    networks:
      - survey-network
  survey-queue:
    image: "rabbitmq:3-management"
    container_name: "survey-queue"
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - survey-network

volumes:
  pg-data:
  shared-storage:

networks:
  survey-network:
    driver: bridge
