FROM python:3.12.8-alpine AS builder

WORKDIR /consumer

COPY requirements.txt .

RUN apk add --no-cache gcc musl-dev && \
    python -m venv /venv && \
    /venv/bin/pip install --no-cache-dir -r requirements.txt && \
    apk del gcc musl-dev


FROM python:3.12.8-alpine

WORKDIR /consumer

RUN addgroup -S appgroup && adduser -S appuser -G appgroup

COPY --from=builder /venv /venv

COPY src/ .

USER appuser

CMD ["/venv/bin/python", "main.py"]